name: Deploy Angular to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/angular-registry/angular-app .
          docker push registry.digitalocean.com/angular-registry/angular-app

      - name: SSH into DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull registry.digitalocean.com/angular-registry/angular-app
            docker stop angular-app || true
            docker rm angular-app || true
            docker run -d --name angular-app -p 80:80 registry.digitalocean.com/angular-registry/angular-app
